# Code for Neuron

In [1]:
import torch
import torch.nn as nn

In [2]:
# Inputs
torch.manual_seed(42) # Random State
inputs = torch.tensor([1.0, 2.0, 3.0])

In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [6]:
# Verify - Direct Formula

neuron.weight @ inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [7]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [8]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)